# Generated by Django 4.2.28 on 2026-02-22 11:26

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Employee',
            fields=[
                ('Employee_Id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('Mobile_Number', models.IntegerField(unique=True)),
                ('Joining_Date', models.CharField(max_length=255)),
                ('Dateof_Birth', models.CharField(max_length=255)),
                ('Departments', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Blood_Group', models.CharField(max_length=255)),
                ('Education', models.CharField(max_length=255)),
                ('Personal_Identity', models.CharField(max_length=255, unique=True)),
                ('Guardian', models.CharField(max_length=255)),
                ('Guardian_Number', models.IntegerField()),
                ('Upload_Image', models.ImageField(upload_to='')),
                ('Address', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Add_Employees',
            },
        ),
        migrations.CreateModel(
            name='Add_Room',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Room_Number', models.CharField(max_length=255, unique=True)),
                ('Room_Type', models.CharField(max_length=255)),
                ('Room_Floor', models.CharField(max_length=255)),
                ('Room_Facility', models.CharField(max_length=500)),
                ('Room_Price', models.CharField(max_length=255)),
                ('Room_Image', models.ImageField(upload_to='')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Add_Room',
            },
        ),
        migrations.CreateModel(
            name='Offline_Booking',
            fields=[
                ('Customer_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Check_in', models.CharField(max_length=255)),
                ('Check_out', models.CharField(max_length=255)),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Mobile_Number', models.IntegerField()),
                ('ADULT', models.CharField(max_length=255)),
                ('CHILDREN', models.CharField(max_length=255)),
                ('Total_Person', models.IntegerField()),
                ('Select_Room', models.CharField(max_length=255)),
                ('Room_Number', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Personal_Identity', models.CharField(max_length=255)),
                ('Upload_Image', models.ImageField(upload_to='')),
                ('Country', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Offline_Booking_Customer',
            },
        ),
        migrations.CreateModel(
            name='Online_Booking',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Check_in', models.CharField(max_length=255)),
                ('Check_out', models.CharField(max_length=255)),
                ('ADULT', models.CharField(max_length=255)),
                ('CHILDREN', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Surname', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Phone_Number', models.IntegerField()),
                ('City', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Nid_No', models.CharField(max_length=255)),
                ('Img', models.ImageField(upload_to='')),
                ('Address', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Online_Booking_table',
            },
        ),
        migrations.CreateModel(
            name='Authorregis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Phone_Number', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Add_Salarys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=255)),
                ('Mobile_Number', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=500)),
                ('Departments', models.CharField(max_length=255)),
                ('Salary', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Employee_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.add_employee')),
            ],
            options={
                'db_table': 'Add_Employee_salarys',
            },
        ),
    ]
