# Generated by Django 4.2.28 on 2026-02-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0002_employee_offlinebooking_onlinebooking_room_salary_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authorregis',
            managers=[
            ],
        ),
    ]
